-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-08-18 17:57:04 BDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Catagory 
    ( 
     catagory_id NUMBER  NOT NULL , 
     name        VARCHAR2 (100) , 
     description VARCHAR2 (500) 
    ) 
;

ALTER TABLE Catagory 
    ADD CONSTRAINT Catagory_PK PRIMARY KEY ( catagory_id ) ;

CREATE TABLE Customer 
    ( 
     customer_id      NUMBER  NOT NULL , 
     customer_name    VARCHAR2 (100) , 
     customer_email   VARCHAR2 (100) , 
     customer_address VARCHAR2 (100) 
    ) 
;

ALTER TABLE Customer 
    ADD CONSTRAINT Customer_PK PRIMARY KEY ( customer_id ) ;

CREATE TABLE Delivery 
    ( 
     delivery_id      NUMBER  NOT NULL , 
     delivery_address VARCHAR2 (200) , 
     delivery_date    DATE , 
     status           VARCHAR2 (30) , 
     courier_name     VARCHAR2 (100) , 
     tracking_number  VARCHAR2 (100) , 
     order_id         NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Delivery 
    ADD CONSTRAINT Delivery_PK PRIMARY KEY ( delivery_id ) ;

CREATE TABLE Inventory 
    ( 
     inventory_id        NUMBER  NOT NULL , 
     stock_quantity      NUMBER , 
     reorder_level       NUMBER , 
     last_updated        DATE , 
     product_id          NUMBER  NOT NULL , 
     supplier_product_id NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Inventory 
    ADD CONSTRAINT Inventory_PK PRIMARY KEY ( inventory_id ) ;

CREATE TABLE "Order" 
    ( 
     order_id     NUMBER  NOT NULL , 
     order_date   DATE , 
     status       VARCHAR2 (30) , 
     total_amount NUMBER , 
     customer_id  NUMBER  NOT NULL 
    ) 
;

ALTER TABLE "Order" 
    ADD CONSTRAINT Order_PK PRIMARY KEY ( order_id ) ;

CREATE TABLE OrderItem 
    ( 
     order_item_id NUMBER  NOT NULL , 
     quantity      NUMBER , 
     unit_price    NUMBER , 
     discount      NUMBER , 
     subtotal      NUMBER , 
     order_id      NUMBER  NOT NULL , 
     product_id    NUMBER  NOT NULL 
    ) 
;

ALTER TABLE OrderItem 
    ADD CONSTRAINT OrderItem_PK PRIMARY KEY ( order_item_id ) ;

CREATE TABLE Payment 
    ( 
     payment_id     NUMBER  NOT NULL , 
     amount         NUMBER , 
     method         VARCHAR2 (30) , 
     paid_at        DATE , 
     status         VARCHAR2 (30) , 
     transaction_id VARCHAR2 (100) , 
     order_id       NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Payment 
    ADD CONSTRAINT Payment_PK PRIMARY KEY ( payment_id ) ;

CREATE TABLE Product 
    ( 
     product_id  NUMBER  NOT NULL , 
     name        VARCHAR2 (100) , 
     description VARCHAR2 (500) , 
     unit_price  NUMBER , 
     status      VARCHAR2 (50) , 
     catagory_id NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Product 
    ADD CONSTRAINT Product_PK PRIMARY KEY ( product_id ) ;

CREATE TABLE Supplier 
    ( 
     supplier_id      NUMBER  NOT NULL , 
     supplier_name    VARCHAR2 (100) , 
     supplier_phone   VARCHAR2 (20) , 
     supplier_email   VARCHAR2 (100) , 
     supplier_address VARCHAR2 (200) 
    ) 
;

ALTER TABLE Supplier 
    ADD CONSTRAINT Supplier_PK PRIMARY KEY ( supplier_id ) ;

CREATE TABLE SupplierProduct 
    ( 
     supplier_product_id NUMBER  NOT NULL , 
     supply_price        NUMBER , 
     lead_time           NUMBER , 
     supplier_id         NUMBER  NOT NULL , 
     product_id          NUMBER  NOT NULL 
    ) 
;

ALTER TABLE SupplierProduct 
    ADD CONSTRAINT SupplierProduct_PK PRIMARY KEY ( supplier_product_id ) ;

ALTER TABLE Delivery 
    ADD CONSTRAINT Delivery_Order_FK FOREIGN KEY 
    ( 
     order_id
    ) 
    REFERENCES "Order" 
    ( 
     order_id
    ) 
;

ALTER TABLE "Order" 
    ADD CONSTRAINT FK_order_customer FOREIGN KEY 
    ( 
     customer_id
    ) 
    REFERENCES Customer 
    ( 
     customer_id
    ) 
;

ALTER TABLE Inventory 
    ADD CONSTRAINT Inventory_Product_FK FOREIGN KEY 
    ( 
     product_id
    ) 
    REFERENCES Product 
    ( 
     product_id
    ) 
;

ALTER TABLE Inventory 
    ADD CONSTRAINT Inventory_SupplierProduct_FK FOREIGN KEY 
    ( 
     supplier_product_id
    ) 
    REFERENCES SupplierProduct 
    ( 
     supplier_product_id
    ) 
;

ALTER TABLE OrderItem 
    ADD CONSTRAINT OrderItem_Order_FK FOREIGN KEY 
    ( 
     order_id
    ) 
    REFERENCES "Order" 
    ( 
     order_id
    ) 
;

ALTER TABLE OrderItem 
    ADD CONSTRAINT OrderItem_Product_FK FOREIGN KEY 
    ( 
     product_id
    ) 
    REFERENCES Product 
    ( 
     product_id
    ) 
;

ALTER TABLE Payment 
    ADD CONSTRAINT Payment_Order_FK FOREIGN KEY 
    ( 
     order_id
    ) 
    REFERENCES "Order" 
    ( 
     order_id
    ) 
;

ALTER TABLE Product 
    ADD CONSTRAINT Product_Catagory_FK FOREIGN KEY 
    ( 
     catagory_id
    ) 
    REFERENCES Catagory 
    ( 
     catagory_id
    ) 
;

ALTER TABLE SupplierProduct 
    ADD CONSTRAINT SupplierProduct_Product_FK FOREIGN KEY 
    ( 
     product_id
    ) 
    REFERENCES Product 
    ( 
     product_id
    ) 
;

ALTER TABLE SupplierProduct 
    ADD CONSTRAINT SupplierProduct_Supplier_FK FOREIGN KEY 
    ( 
     supplier_id
    ) 
    REFERENCES Supplier 
    ( 
     supplier_id
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             20
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
